# Generated by Django 6.0.2 on 2026-03-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_achievement_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainabilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('feature_importance', models.JSONField(default=dict)),
                ('model_reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explainability', to='user.case')),
            ],
        ),
    ]
