# Generated by Django 6.0.2 on 2026-03-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_explainabilitydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='file_uri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
