# Generated by Django 6.0.2 on 2026-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_case_file_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='clinical_recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
