# Generated by Django 6.0.2 on 2026-03-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_case_clinical_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
