# Generated by Django 6.0.2 on 2026-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='color_hex',
            field=models.CharField(default='#FEF9C3', max_length=7),
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon_slug',
            field=models.CharField(default='ic_star_badge', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='five_year_insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='follow_up_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='health_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='one_year_insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='three_year_insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='include_experimental_models',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prediction_sensitivity',
            field=models.CharField(default='Standard (Balanced)', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PROVIDER', 'Healthcare Provider'), ('PATIENT', 'Patient'), ('LAB', 'Lab Technician')], default='PROVIDER', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_confidence_intervals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='explainabilitydata',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='case',
            name='five_year_prediction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='five_year_risk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='one_year_prediction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='one_year_risk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='three_year_prediction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='three_year_risk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(default='INFO', max_length=50),
        ),
    ]
