# Generated by Django 6.0.3 on 2026-03-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_faq_legaldocument_achievement_color_hex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='xp_points',
            field=models.IntegerField(default=0),
        ),
    ]
