# Generated by Django 6.0.3 on 2026-03-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customuser_xp_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='fibrous_tissue_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='case',
            name='healthy_tissue_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='case',
            name='inflamed_tissue_pct',
            field=models.FloatField(default=0.0),
        ),
    ]
